services:
  - type: web
    name: laravel-app
    env: docker
    branch: main
    region: oregon
    buildCommand: ""
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:+0lBtZH74nYWqUPrT7IalAb7koiR5kLNMIsQeqxC/cY=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: estoque
      - key: DB_USERNAME
        value: estudo
      - key: DB_PASSWORD
        value: 071715
